module.exports = {
    "latitude": 37.8267,
    "longitude": -122.4233,
    "timezone": "America/Los_Angeles",
    "currently": {
        "time": 1531951040,
        "summary": "Clear",
        "icon": "clear-day",
        "nearestStormDistance": 25,
        "nearestStormBearing": 341,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 70.03,
        "apparentTemperature": 70.03,
        "dewPoint": 57.41,
        "humidity": 0.64,
        "pressure": 1014.19,
        "windSpeed": 9.05,
        "windGust": 14.47,
        "windBearing": 246,
        "cloudCover": 0.21,
        "uvIndex": 7,
        "visibility": 10,
        "ozone": 299.3
    },
    "minutely": {
        "summary": "Clear for the hour.",
        "icon": "clear-day",
        "data": [{
            "time": 1531951020,
            "precipIntensity": 0,
            "precipProbability": 0
        },
            {
                "time": 1531951080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531951980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531952940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531953960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1531954620,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Partly cloudy this evening.",
        "icon": "partly-cloudy-day",
        "data": [{
            "time": 1531947600,
            "summary": "Partly Cloudy",
            "icon": "partly-cloudy-day",
            "precipIntensity": 0,
            "precipProbability": 0,
            "temperature": 68.98,
            "apparentTemperature": 68.98,
            "dewPoint": 57.77,
            "humidity": 0.68,
            "pressure": 1014.68,
            "windSpeed": 8.86,
            "windGust": 14.26,
            "windBearing": 245,
            "cloudCover": 0.28,
            "uvIndex": 9,
            "visibility": 9.74,
            "ozone": 300.03
        },
            {
                "time": 1531951200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 70.07,
                "apparentTemperature": 70.07,
                "dewPoint": 57.39,
                "humidity": 0.64,
                "pressure": 1014.17,
                "windSpeed": 9.05,
                "windGust": 14.48,
                "windBearing": 246,
                "cloudCover": 0.21,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 299.27
            },
            {
                "time": 1531954800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.96,
                "apparentTemperature": 69.96,
                "dewPoint": 56.86,
                "humidity": 0.63,
                "pressure": 1013.66,
                "windSpeed": 9,
                "windGust": 13.73,
                "windBearing": 249,
                "cloudCover": 0.19,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 298.49
            },
            {
                "time": 1531958400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0013,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 68.57,
                "apparentTemperature": 68.57,
                "dewPoint": 56.15,
                "humidity": 0.65,
                "pressure": 1013.12,
                "windSpeed": 8.49,
                "windGust": 12.29,
                "windBearing": 246,
                "cloudCover": 0.25,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 297.74
            },
            {
                "time": 1531962000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67,
                "apparentTemperature": 67,
                "dewPoint": 55.89,
                "humidity": 0.68,
                "pressure": 1012.65,
                "windSpeed": 7.91,
                "windGust": 11.18,
                "windBearing": 243,
                "cloudCover": 0.27,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 297.04
            },
            {
                "time": 1531965600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0017,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 65.01,
                "apparentTemperature": 65.01,
                "dewPoint": 56.03,
                "humidity": 0.73,
                "pressure": 1012.43,
                "windSpeed": 7.44,
                "windGust": 10.69,
                "windBearing": 240,
                "cloudCover": 0.24,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 296.36
            },
            {
                "time": 1531969200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.88,
                "apparentTemperature": 62.88,
                "dewPoint": 56.09,
                "humidity": 0.79,
                "pressure": 1012.39,
                "windSpeed": 6.89,
                "windGust": 9.98,
                "windBearing": 238,
                "cloudCover": 0.22,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.9
            },
            {
                "time": 1531972800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0013,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 60.96,
                "apparentTemperature": 60.96,
                "dewPoint": 56.03,
                "humidity": 0.84,
                "pressure": 1012.76,
                "windSpeed": 6.66,
                "windGust": 9.73,
                "windBearing": 229,
                "cloudCover": 0.26,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.66
            },
            {
                "time": 1531976400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 59.75,
                "apparentTemperature": 59.75,
                "dewPoint": 55.69,
                "humidity": 0.86,
                "pressure": 1013.16,
                "windSpeed": 6.88,
                "windGust": 9.73,
                "windBearing": 221,
                "cloudCover": 0.28,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.67
            },
            {
                "time": 1531980000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0016,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 59.03,
                "apparentTemperature": 59.03,
                "dewPoint": 55.33,
                "humidity": 0.88,
                "pressure": 1013.45,
                "windSpeed": 6.69,
                "windGust": 9.73,
                "windBearing": 220,
                "cloudCover": 0.35,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.69
            },
            {
                "time": 1531983600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.59,
                "apparentTemperature": 58.59,
                "dewPoint": 54.98,
                "humidity": 0.88,
                "pressure": 1013.21,
                "windSpeed": 6.45,
                "windGust": 9.7,
                "windBearing": 222,
                "cloudCover": 0.48,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.78
            },
            {
                "time": 1531987200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0006,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 58.23,
                "apparentTemperature": 58.23,
                "dewPoint": 54.79,
                "humidity": 0.88,
                "pressure": 1012.88,
                "windSpeed": 6.14,
                "windGust": 10.15,
                "windBearing": 225,
                "cloudCover": 0.62,
                "uvIndex": 0,
                "visibility": 9.22,
                "ozone": 295.92
            },
            {
                "time": 1531990800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.001,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.68,
                "apparentTemperature": 57.68,
                "dewPoint": 54.7,
                "humidity": 0.9,
                "pressure": 1012.62,
                "windSpeed": 5.96,
                "windGust": 10.38,
                "windBearing": 225,
                "cloudCover": 0.71,
                "uvIndex": 0,
                "visibility": 8.01,
                "ozone": 296.03
            },
            {
                "time": 1531994400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0016,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.18,
                "apparentTemperature": 57.18,
                "dewPoint": 54.5,
                "humidity": 0.91,
                "pressure": 1012.47,
                "windSpeed": 5.83,
                "windGust": 10.26,
                "windBearing": 223,
                "cloudCover": 0.74,
                "uvIndex": 0,
                "visibility": 8.06,
                "ozone": 295.99
            },
            {
                "time": 1531998000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0006,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 56.56,
                "apparentTemperature": 56.56,
                "dewPoint": 54.37,
                "humidity": 0.92,
                "pressure": 1012.46,
                "windSpeed": 5.73,
                "windGust": 9.66,
                "windBearing": 220,
                "cloudCover": 0.73,
                "uvIndex": 0,
                "visibility": 8.35,
                "ozone": 295.85
            },
            {
                "time": 1532001600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0007,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 55.3,
                "apparentTemperature": 55.3,
                "dewPoint": 53.92,
                "humidity": 0.95,
                "pressure": 1012.24,
                "windSpeed": 5.29,
                "windGust": 7.24,
                "windBearing": 214,
                "cloudCover": 0.87,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.78
            },
            {
                "time": 1532005200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0005,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 55.08,
                "apparentTemperature": 55.08,
                "dewPoint": 53.84,
                "humidity": 0.96,
                "pressure": 1012.37,
                "windSpeed": 4.82,
                "windGust": 6.5,
                "windBearing": 206,
                "cloudCover": 0.89,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.77
            },
            {
                "time": 1532008800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 55.08,
                "apparentTemperature": 55.08,
                "dewPoint": 53.79,
                "humidity": 0.95,
                "pressure": 1012.56,
                "windSpeed": 4.04,
                "windGust": 5.47,
                "windBearing": 210,
                "cloudCover": 0.92,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 295.81
            },
            {
                "time": 1532012400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.65,
                "apparentTemperature": 55.65,
                "dewPoint": 53.78,
                "humidity": 0.93,
                "pressure": 1012.78,
                "windSpeed": 3.62,
                "windGust": 4.8,
                "windBearing": 210,
                "cloudCover": 0.93,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 295.93
            },
            {
                "time": 1532016000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 57.7,
                "apparentTemperature": 57.7,
                "dewPoint": 53.87,
                "humidity": 0.87,
                "pressure": 1012.95,
                "windSpeed": 3.83,
                "windGust": 4.62,
                "windBearing": 212,
                "cloudCover": 0.86,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 296.1
            },
            {
                "time": 1532019600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.61,
                "apparentTemperature": 60.61,
                "dewPoint": 54.03,
                "humidity": 0.79,
                "pressure": 1013.17,
                "windSpeed": 4.17,
                "windGust": 4.82,
                "windBearing": 220,
                "cloudCover": 0.74,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 296.36
            },
            {
                "time": 1532023200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 63.3,
                "apparentTemperature": 63.3,
                "dewPoint": 54.22,
                "humidity": 0.72,
                "pressure": 1013.27,
                "windSpeed": 4.8,
                "windGust": 5.42,
                "windBearing": 228,
                "cloudCover": 0.71,
                "uvIndex": 4,
                "visibility": 10,
                "ozone": 296.83
            },
            {
                "time": 1532026800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.58,
                "apparentTemperature": 65.58,
                "dewPoint": 54.46,
                "humidity": 0.67,
                "pressure": 1013.31,
                "windSpeed": 5.7,
                "windGust": 6.84,
                "windBearing": 232,
                "cloudCover": 0.64,
                "uvIndex": 6,
                "visibility": 10,
                "ozone": 297.4
            },
            {
                "time": 1532030400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.29,
                "apparentTemperature": 67.29,
                "dewPoint": 54.73,
                "humidity": 0.64,
                "pressure": 1013.17,
                "windSpeed": 6.69,
                "windGust": 8.83,
                "windBearing": 237,
                "cloudCover": 0.58,
                "uvIndex": 8,
                "visibility": 10,
                "ozone": 298.18
            },
            {
                "time": 1532034000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.21,
                "apparentTemperature": 68.21,
                "dewPoint": 54.99,
                "humidity": 0.63,
                "pressure": 1012.91,
                "windSpeed": 7.72,
                "windGust": 10.49,
                "windBearing": 238,
                "cloudCover": 0.64,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 299.16
            },
            {
                "time": 1532037600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.01,
                "apparentTemperature": 68.01,
                "dewPoint": 55.21,
                "humidity": 0.64,
                "pressure": 1012.6,
                "windSpeed": 8.3,
                "windGust": 11.58,
                "windBearing": 241,
                "cloudCover": 0.72,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 300.45
            },
            {
                "time": 1532041200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 67.6,
                "apparentTemperature": 67.6,
                "dewPoint": 55.43,
                "humidity": 0.65,
                "pressure": 1012.29,
                "windSpeed": 8.59,
                "windGust": 12.35,
                "windBearing": 236,
                "cloudCover": 0.73,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 301.86
            },
            {
                "time": 1532044800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 66.69,
                "apparentTemperature": 66.69,
                "dewPoint": 55.61,
                "humidity": 0.68,
                "pressure": 1012.03,
                "windSpeed": 8.46,
                "windGust": 12.58,
                "windBearing": 239,
                "cloudCover": 0.71,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 303.35
            },
            {
                "time": 1532048400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 65.56,
                "apparentTemperature": 65.56,
                "dewPoint": 55.74,
                "humidity": 0.71,
                "pressure": 1011.8,
                "windSpeed": 8.16,
                "windGust": 12.04,
                "windBearing": 242,
                "cloudCover": 0.67,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 305
            },
            {
                "time": 1532052000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 63.77,
                "apparentTemperature": 63.77,
                "dewPoint": 55.82,
                "humidity": 0.75,
                "pressure": 1011.6,
                "windSpeed": 7.57,
                "windGust": 11,
                "windBearing": 244,
                "cloudCover": 0.49,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 306.68
            },
            {
                "time": 1532055600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.09,
                "apparentTemperature": 62.09,
                "dewPoint": 55.86,
                "humidity": 0.8,
                "pressure": 1011.49,
                "windSpeed": 6.99,
                "windGust": 10.1,
                "windBearing": 245,
                "cloudCover": 0.38,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 307.7
            },
            {
                "time": 1532059200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.82,
                "apparentTemperature": 60.82,
                "dewPoint": 55.85,
                "humidity": 0.84,
                "pressure": 1011.66,
                "windSpeed": 6.63,
                "windGust": 9.54,
                "windBearing": 243,
                "cloudCover": 0.43,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 307.43
            },
            {
                "time": 1532062800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 60.25,
                "apparentTemperature": 60.25,
                "dewPoint": 55.81,
                "humidity": 0.85,
                "pressure": 1012.03,
                "windSpeed": 6.34,
                "windGust": 9.13,
                "windBearing": 240,
                "cloudCover": 0.48,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 306.48
            },
            {
                "time": 1532066400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 59.92,
                "apparentTemperature": 59.92,
                "dewPoint": 55.75,
                "humidity": 0.86,
                "pressure": 1012.28,
                "windSpeed": 6.02,
                "windGust": 8.87,
                "windBearing": 236,
                "cloudCover": 0.51,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 305.53
            },
            {
                "time": 1532070000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 59.64,
                "apparentTemperature": 59.64,
                "dewPoint": 55.67,
                "humidity": 0.87,
                "pressure": 1012.36,
                "windSpeed": 5.91,
                "windGust": 8.91,
                "windBearing": 233,
                "cloudCover": 0.52,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 304.88
            },
            {
                "time": 1532073600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 59.35,
                "apparentTemperature": 59.35,
                "dewPoint": 55.59,
                "humidity": 0.87,
                "pressure": 1012.36,
                "windSpeed": 5.79,
                "windGust": 9.15,
                "windBearing": 229,
                "cloudCover": 0.54,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 304.21
            },
            {
                "time": 1532077200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 58.82,
                "apparentTemperature": 58.82,
                "dewPoint": 55.51,
                "humidity": 0.89,
                "pressure": 1012.3,
                "windSpeed": 5.64,
                "windGust": 9.2,
                "windBearing": 226,
                "cloudCover": 0.57,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.77
            },
            {
                "time": 1532080800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 58.12,
                "apparentTemperature": 58.12,
                "dewPoint": 55.4,
                "humidity": 0.91,
                "pressure": 1012.21,
                "windSpeed": 5.46,
                "windGust": 8.94,
                "windBearing": 221,
                "cloudCover": 0.57,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.33
            },
            {
                "time": 1532084400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.35,
                "apparentTemperature": 57.35,
                "dewPoint": 55.32,
                "humidity": 0.93,
                "pressure": 1012.12,
                "windSpeed": 5.04,
                "windGust": 8.52,
                "windBearing": 227,
                "cloudCover": 0.61,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.05
            },
            {
                "time": 1532088000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.06,
                "apparentTemperature": 57.06,
                "dewPoint": 55.32,
                "humidity": 0.94,
                "pressure": 1012.13,
                "windSpeed": 4.78,
                "windGust": 8.08,
                "windBearing": 228,
                "cloudCover": 0.6,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.94
            },
            {
                "time": 1532091600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.14,
                "apparentTemperature": 57.14,
                "dewPoint": 55.45,
                "humidity": 0.94,
                "pressure": 1012.37,
                "windSpeed": 4.19,
                "windGust": 7.59,
                "windBearing": 230,
                "cloudCover": 0.62,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.1
            },
            {
                "time": 1532095200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 57.69,
                "apparentTemperature": 57.69,
                "dewPoint": 55.66,
                "humidity": 0.93,
                "pressure": 1012.69,
                "windSpeed": 3.52,
                "windGust": 7.11,
                "windBearing": 235,
                "cloudCover": 0.6,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 303.43
            },
            {
                "time": 1532098800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 58.65,
                "apparentTemperature": 58.65,
                "dewPoint": 55.94,
                "humidity": 0.91,
                "pressure": 1013.07,
                "windSpeed": 3.26,
                "windGust": 6.81,
                "windBearing": 238,
                "cloudCover": 0.58,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 303.65
            },
            {
                "time": 1532102400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 60.28,
                "apparentTemperature": 60.28,
                "dewPoint": 56.3,
                "humidity": 0.87,
                "pressure": 1013.35,
                "windSpeed": 3.13,
                "windGust": 6.73,
                "windBearing": 244,
                "cloudCover": 0.46,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 303.38
            },
            {
                "time": 1532106000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 62.31,
                "apparentTemperature": 62.31,
                "dewPoint": 56.71,
                "humidity": 0.82,
                "pressure": 1013.63,
                "windSpeed": 4.01,
                "windGust": 6.82,
                "windBearing": 232,
                "cloudCover": 0.56,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 303.01
            },
            {
                "time": 1532109600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 64.43,
                "apparentTemperature": 64.43,
                "dewPoint": 57.12,
                "humidity": 0.77,
                "pressure": 1013.79,
                "windSpeed": 4.67,
                "windGust": 7.2,
                "windBearing": 240,
                "cloudCover": 0.52,
                "uvIndex": 5,
                "visibility": 10,
                "ozone": 302.85
            },
            {
                "time": 1532113200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 66.32,
                "apparentTemperature": 66.32,
                "dewPoint": 57.51,
                "humidity": 0.73,
                "pressure": 1013.83,
                "windSpeed": 5.56,
                "windGust": 8.11,
                "windBearing": 242,
                "cloudCover": 0.48,
                "uvIndex": 7,
                "visibility": 10,
                "ozone": 303.09
            },
            {
                "time": 1532116800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 68.28,
                "apparentTemperature": 68.28,
                "dewPoint": 57.89,
                "humidity": 0.69,
                "pressure": 1013.81,
                "windSpeed": 6.72,
                "windGust": 9.35,
                "windBearing": 243,
                "cloudCover": 0.35,
                "uvIndex": 9,
                "visibility": 10,
                "ozone": 303.62
            },
            {
                "time": 1532120400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 69.57,
                "apparentTemperature": 69.57,
                "dewPoint": 58.15,
                "humidity": 0.67,
                "pressure": 1013.65,
                "windSpeed": 7.73,
                "windGust": 10.43,
                "windBearing": 242,
                "cloudCover": 0.24,
                "uvIndex": 9,
                "visibility": 10,
                "ozone": 304.11
            }
        ]
    },
    "daily": {
        "summary": "No precipitation throughout the week, with high temperatures rising to 72°F on Tuesday.",
        "icon": "clear-day",
        "data": [{
            "time": 1531897200,
            "summary": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "sunriseTime": 1531918995,
            "sunsetTime": 1531971055,
            "moonPhase": 0.21,
            "precipIntensity": 0.0003,
            "precipIntensityMax": 0.0018,
            "precipIntensityMaxTime": 1531897200,
            "precipProbability": 0.06,
            "precipType": "rain",
            "temperatureHigh": 70.07,
            "temperatureHighTime": 1531951200,
            "temperatureLow": 55.08,
            "temperatureLowTime": 1532005200,
            "apparentTemperatureHigh": 70.07,
            "apparentTemperatureHighTime": 1531951200,
            "apparentTemperatureLow": 55.08,
            "apparentTemperatureLowTime": 1532005200,
            "dewPoint": 55.61,
            "humidity": 0.81,
            "pressure": 1014.5,
            "windSpeed": 6.29,
            "windGust": 14.48,
            "windGustTime": 1531951200,
            "windBearing": 241,
            "cloudCover": 0.49,
            "uvIndex": 9,
            "uvIndexTime": 1531944000,
            "visibility": 10,
            "ozone": 299.48,
            "temperatureMin": 54.54,
            "temperatureMinTime": 1531911600,
            "temperatureMax": 70.07,
            "temperatureMaxTime": 1531951200,
            "apparentTemperatureMin": 54.54,
            "apparentTemperatureMinTime": 1531911600,
            "apparentTemperatureMax": 70.07,
            "apparentTemperatureMaxTime": 1531951200
        },
            {
                "time": 1531983600,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1532005441,
                "sunsetTime": 1532057418,
                "moonPhase": 0.25,
                "precipIntensity": 0.0003,
                "precipIntensityMax": 0.0016,
                "precipIntensityMaxTime": 1531994400,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperatureHigh": 68.21,
                "temperatureHighTime": 1532034000,
                "temperatureLow": 57.06,
                "temperatureLowTime": 1532088000,
                "apparentTemperatureHigh": 68.21,
                "apparentTemperatureHighTime": 1532034000,
                "apparentTemperatureLow": 57.06,
                "apparentTemperatureLowTime": 1532088000,
                "dewPoint": 54.83,
                "humidity": 0.81,
                "pressure": 1012.51,
                "windSpeed": 6.04,
                "windGust": 12.58,
                "windGustTime": 1532044800,
                "windBearing": 231,
                "cloudCover": 0.67,
                "uvIndex": 8,
                "uvIndexTime": 1532030400,
                "visibility": 10,
                "ozone": 299.64,
                "temperatureMin": 55.08,
                "temperatureMinTime": 1532005200,
                "temperatureMax": 68.21,
                "temperatureMaxTime": 1532034000,
                "apparentTemperatureMin": 55.08,
                "apparentTemperatureMinTime": 1532005200,
                "apparentTemperatureMax": 68.21,
                "apparentTemperatureMaxTime": 1532034000
            },
            {
                "time": 1532070000,
                "summary": "Partly cloudy until afternoon.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1532091887,
                "sunsetTime": 1532143779,
                "moonPhase": 0.28,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1532095200,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperatureHigh": 70.39,
                "temperatureHighTime": 1532127600,
                "temperatureLow": 59.33,
                "temperatureLowTime": 1532178000,
                "apparentTemperatureHigh": 70.39,
                "apparentTemperatureHighTime": 1532127600,
                "apparentTemperatureLow": 59.33,
                "apparentTemperatureLowTime": 1532178000,
                "dewPoint": 56.83,
                "humidity": 0.81,
                "pressure": 1012.97,
                "windSpeed": 5.87,
                "windGust": 12.26,
                "windGustTime": 1532131200,
                "windBearing": 238,
                "cloudCover": 0.39,
                "uvIndex": 9,
                "uvIndexTime": 1532116800,
                "visibility": 10,
                "ozone": 303.94,
                "temperatureMin": 57.06,
                "temperatureMinTime": 1532088000,
                "temperatureMax": 70.39,
                "temperatureMaxTime": 1532127600,
                "apparentTemperatureMin": 57.06,
                "apparentTemperatureMinTime": 1532088000,
                "apparentTemperatureMax": 70.39,
                "apparentTemperatureMaxTime": 1532127600
            },
            {
                "time": 1532156400,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1532178333,
                "sunsetTime": 1532230139,
                "moonPhase": 0.31,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1532167200,
                "precipProbability": 0.07,
                "precipType": "rain",
                "temperatureHigh": 70.37,
                "temperatureHighTime": 1532210400,
                "temperatureLow": 60.13,
                "temperatureLowTime": 1532268000,
                "apparentTemperatureHigh": 70.37,
                "apparentTemperatureHighTime": 1532210400,
                "apparentTemperatureLow": 60.15,
                "apparentTemperatureLowTime": 1532268000,
                "dewPoint": 57.44,
                "humidity": 0.8,
                "pressure": 1015.09,
                "windSpeed": 6.39,
                "windGust": 12.94,
                "windGustTime": 1532217600,
                "windBearing": 241,
                "cloudCover": 0.51,
                "uvIndex": 9,
                "uvIndexTime": 1532203200,
                "visibility": 10,
                "ozone": 302.69,
                "temperatureMin": 59.33,
                "temperatureMinTime": 1532178000,
                "temperatureMax": 70.37,
                "temperatureMaxTime": 1532210400,
                "apparentTemperatureMin": 59.33,
                "apparentTemperatureMinTime": 1532178000,
                "apparentTemperatureMax": 70.37,
                "apparentTemperatureMaxTime": 1532210400
            },
            {
                "time": 1532242800,
                "summary": "Mostly cloudy in the morning.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1532264781,
                "sunsetTime": 1532316497,
                "moonPhase": 0.35,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1532257200,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperatureHigh": 71.75,
                "temperatureHighTime": 1532296800,
                "temperatureLow": 57.59,
                "temperatureLowTime": 1532350800,
                "apparentTemperatureHigh": 71.75,
                "apparentTemperatureHighTime": 1532296800,
                "apparentTemperatureLow": 57.59,
                "apparentTemperatureLowTime": 1532350800,
                "dewPoint": 57.26,
                "humidity": 0.77,
                "pressure": 1016.54,
                "windSpeed": 4.86,
                "windGust": 12.29,
                "windGustTime": 1532304000,
                "windBearing": 237,
                "cloudCover": 0.36,
                "uvIndex": 10,
                "uvIndexTime": 1532289600,
                "visibility": 10,
                "ozone": 304.36,
                "temperatureMin": 60.13,
                "temperatureMinTime": 1532268000,
                "temperatureMax": 71.75,
                "temperatureMaxTime": 1532296800,
                "apparentTemperatureMin": 60.15,
                "apparentTemperatureMinTime": 1532268000,
                "apparentTemperatureMax": 71.75,
                "apparentTemperatureMaxTime": 1532296800
            },
            {
                "time": 1532329200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1532351229,
                "sunsetTime": 1532402853,
                "moonPhase": 0.38,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0005,
                "precipIntensityMaxTime": 1532354400,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperatureHigh": 71.75,
                "temperatureHighTime": 1532383200,
                "temperatureLow": 58.46,
                "temperatureLowTime": 1532440800,
                "apparentTemperatureHigh": 71.75,
                "apparentTemperatureHighTime": 1532383200,
                "apparentTemperatureLow": 58.46,
                "apparentTemperatureLowTime": 1532440800,
                "dewPoint": 55.76,
                "humidity": 0.76,
                "pressure": 1016.26,
                "windSpeed": 4.84,
                "windGust": 13.06,
                "windGustTime": 1532390400,
                "windBearing": 245,
                "cloudCover": 0,
                "uvIndex": 11,
                "uvIndexTime": 1532376000,
                "visibility": 10,
                "ozone": 300.42,
                "temperatureMin": 57.59,
                "temperatureMinTime": 1532350800,
                "temperatureMax": 71.75,
                "temperatureMaxTime": 1532383200,
                "apparentTemperatureMin": 57.59,
                "apparentTemperatureMinTime": 1532350800,
                "apparentTemperatureMax": 71.75,
                "apparentTemperatureMaxTime": 1532383200
            },
            {
                "time": 1532415600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1532437677,
                "sunsetTime": 1532489208,
                "moonPhase": 0.41,
                "precipIntensity": 0.0002,
                "precipIntensityMax": 0.0007,
                "precipIntensityMaxTime": 1532440800,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperatureHigh": 72.45,
                "temperatureHighTime": 1532473200,
                "temperatureLow": 58.57,
                "temperatureLowTime": 1532523600,
                "apparentTemperatureHigh": 72.45,
                "apparentTemperatureHighTime": 1532473200,
                "apparentTemperatureLow": 58.57,
                "apparentTemperatureLowTime": 1532523600,
                "dewPoint": 56.46,
                "humidity": 0.76,
                "pressure": 1015.3,
                "windSpeed": 5.52,
                "windGust": 11.44,
                "windGustTime": 1532473200,
                "windBearing": 246,
                "cloudCover": 0,
                "uvIndex": 11,
                "uvIndexTime": 1532462400,
                "visibility": 10,
                "ozone": 297.4,
                "temperatureMin": 58.46,
                "temperatureMinTime": 1532440800,
                "temperatureMax": 72.45,
                "temperatureMaxTime": 1532473200,
                "apparentTemperatureMin": 58.46,
                "apparentTemperatureMinTime": 1532440800,
                "apparentTemperatureMax": 72.45,
                "apparentTemperatureMaxTime": 1532473200
            },
            {
                "time": 1532502000,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1532524126,
                "sunsetTime": 1532575561,
                "moonPhase": 0.44,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureHigh": 71.85,
                "temperatureHighTime": 1532556000,
                "temperatureLow": 57.82,
                "temperatureLowTime": 1532613600,
                "apparentTemperatureHigh": 71.85,
                "apparentTemperatureHighTime": 1532556000,
                "apparentTemperatureLow": 57.82,
                "apparentTemperatureLowTime": 1532613600,
                "dewPoint": 56.07,
                "humidity": 0.76,
                "pressure": 1014.66,
                "windSpeed": 5.85,
                "windGust": 11.23,
                "windGustTime": 1532563200,
                "windBearing": 243,
                "cloudCover": 0.01,
                "uvIndex": 11,
                "uvIndexTime": 1532548800,
                "visibility": 10,
                "ozone": 292.59,
                "temperatureMin": 58.57,
                "temperatureMinTime": 1532523600,
                "temperatureMax": 71.85,
                "temperatureMaxTime": 1532556000,
                "apparentTemperatureMin": 58.57,
                "apparentTemperatureMinTime": 1532523600,
                "apparentTemperatureMax": 71.85,
                "apparentTemperatureMaxTime": 1532556000
            }
        ]
    },
    "flags": {
        "sources": [
            "nearest-precip",
            "nwspa",
            "cmc",
            "gfs",
            "hrrr",
            "icon",
            "isd",
            "madis",
            "nam",
            "sref",
            "darksky"
        ],
        "nearest-station": 1.839,
        "units": "us"
    },
    "offset": -7
}